version: 0.2

env:
  variables:
    nodeversion: 18
    pythonversion: 3.8

phases:
  install:
    runtime-versions:
      python: $pythonversion
      nodejs: $nodeversion

  build:
    commands:
      - bash scripts/deploy.sh